// ============================================
// UPTIKALERTS — chatInboxStyles.js
// Styles for ChatInbox component
// ============================================

export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    overflow: 'hidden',
    background: 'var(--bg)',
  },
  header: {
    padding: '14px 16px 12px',
    background: '#132d52',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 700,
    color: '#fff',
    fontFamily: 'Outfit, sans-serif',
  },
  scrollArea: {
    flex: 1,
    overflowY: 'auto',
    WebkitOverflowScrolling: 'touch',
    padding: '16px',
  },
  card: {
    background: 'var(--card)',
    borderRadius: 16,
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(0,0,0,0.07)',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 16px',
    cursor: 'pointer',
    borderBottom: '1px solid var(--border)',
    transition: 'background 0.1s',
    background: 'transparent',
  },
  rowActive: {
    background: 'rgba(94, 237, 138, 0.07)',
  },
  iconWrap: {
    width: 36,
    height: 36,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  rowContent: {
    flex: 1,
    minWidth: 0,
  },
  nameRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 6,
    marginBottom: 3,
  },
  name: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--text1)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    flex: 1,
    minWidth: 0,
  },
  time: {
    fontSize: 11,
    color: 'var(--text3)',
    flexShrink: 0,
  },
  preview: {
    fontSize: 13,
    color: 'var(--text3)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  privateDivider: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 16px',
    background: '#f0f4f8',
    cursor: 'pointer',
    borderBottom: '1px solid var(--border)',
    userSelect: 'none',
  },
  privateDividerText: {
    fontSize: 13,
    fontWeight: 600,
    color: '#475569',
    flex: 1,
  },
  chevron: {
    color: '#64748b',
    display: 'flex',
    alignItems: 'center',
  },
  newGroupRow: {
    display: 'flex',
    justifyContent: 'center',
    padding: '14px 16px',
  },
  newGroupBtn: {
    background: 'transparent',
    color: '#132d52',
    border: '1.5px solid #132d52',
    borderRadius: 8,
    padding: '8px 24px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
};
