// ============================================
// UPTIKALERTS — chatInboxStyles.js
// Styles for ChatInbox component
// ============================================

export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    overflow: 'hidden',
    background: 'var(--bg)',
  },
  header: {
    padding: '14px 16px 12px',
    borderBottom: '1px solid var(--border)',
    background: 'var(--card)',
    flexShrink: 0,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 700,
    color: 'var(--text1)',
  },
  scrollArea: {
    flex: 1,
    overflowY: 'auto',
    WebkitOverflowScrolling: 'touch',
  },
  sectionLabel: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 1.2,
    color: 'var(--text3)',
    padding: '14px 16px 5px',
    textTransform: 'uppercase',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '11px 16px',
    cursor: 'pointer',
    borderBottom: '1px solid var(--border)',
    transition: 'background 0.1s',
    background: 'transparent',
  },
  rowUnread: {
    background: 'rgba(94, 237, 138, 0.04)',
  },
  rowActive: {
    background: 'rgba(94, 237, 138, 0.07)',
  },
  groupAvatar: {
    width: 42,
    height: 42,
    borderRadius: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
    fontWeight: 700,
    color: '#fff',
    flexShrink: 0,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
    fontWeight: 700,
    color: '#fff',
    flexShrink: 0,
  },
  onlineDot: {
    position: 'absolute',
    bottom: 1,
    right: 1,
    width: 10,
    height: 10,
    borderRadius: '50%',
    background: '#22c55e',
    border: '2px solid var(--bg)',
  },
  rowContent: {
    flex: 1,
    minWidth: 0,
  },
  nameRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 6,
    marginBottom: 3,
  },
  name: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--text1)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    flex: 1,
    minWidth: 0,
  },
  timeLockRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  time: {
    fontSize: 11,
    color: 'var(--text3)',
  },
  lockIcon: {
    fontSize: 10,
  },
  publicBadge: {
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: 0.5,
    color: '#22c55e',
    background: 'rgba(34, 197, 94, 0.12)',
    padding: '1px 5px',
    borderRadius: 4,
  },
  preview: {
    fontSize: 13,
    color: 'var(--text3)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  previewUnread: {
    color: 'var(--text1)',
    fontWeight: 500,
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: '#5eed8a',
    flexShrink: 0,
    marginLeft: 4,
  },
  badge: {
    background: '#5eed8a',
    color: '#0a1628',
    fontSize: 11,
    fontWeight: 700,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 6px',
    flexShrink: 0,
  },
  toggleRow: {
    padding: '10px 16px',
    cursor: 'pointer',
    borderBottom: '1px solid var(--border)',
    display: 'flex',
    alignItems: 'center',
  },
  toggleText: {
    fontSize: 13,
    color: 'var(--green, #22c55e)',
    fontWeight: 500,
  },
  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 24px',
    gap: 8,
  },
  emptyIcon: {
    fontSize: 36,
    marginBottom: 4,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: 'var(--text1)',
  },
  emptyHint: {
    fontSize: 13,
    color: 'var(--text3)',
    textAlign: 'center',
    lineHeight: 1.5,
  },
  bottomBar: {
    display: 'flex',
    gap: 10,
    padding: '10px 14px',
    borderTop: '1px solid var(--border)',
    background: 'var(--card)',
    flexShrink: 0,
  },
  actionBtn: {
    flex: 1,
    padding: '10px 0',
    background: '#132d52',
    color: '#fff',
    border: 'none',
    borderRadius: 10,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  actionBtnSecondary: {
    flex: 1,
    padding: '10px 0',
    background: 'var(--card2)',
    color: 'var(--text1)',
    border: '1px solid var(--border)',
    borderRadius: 10,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
};
