// ============================================
// UPTIKALERTS — chatInboxStyles.js
// Styles for ChatInbox component
// ============================================

export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    overflow: 'hidden',
    background: 'var(--bg)',
  },
  header: {
    padding: '14px 16px 12px',
    borderBottom: '1px solid var(--border)',
    background: '#132d52',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 700,
    color: '#fff',
  },
  newBtn: {
    background: 'rgba(255,255,255,0.15)',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '6px 14px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  newDropdown: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: 6,
    background: 'var(--card)',
    border: '1px solid var(--border)',
    borderRadius: 10,
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0,0,0,0.15)',
    zIndex: 100,
    minWidth: 180,
  },
  dropdownItem: {
    padding: '12px 16px',
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text1)',
    cursor: 'pointer',
    borderBottom: '1px solid var(--border)',
  },
  nudgeCard: {
    margin: '16px',
    padding: '20px 16px',
    background: 'rgba(19,45,82,0.06)',
    border: '1px solid rgba(19,45,82,0.12)',
    borderRadius: 14,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 6,
    textAlign: 'center',
  },
  nudgeIcon: {
    fontSize: 28,
    marginBottom: 4,
  },
  nudgeTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: 'var(--text1)',
  },
  nudgeHint: {
    fontSize: 13,
    color: 'var(--text3)',
    lineHeight: 1.4,
  },
  nudgeBtn: {
    marginTop: 8,
    padding: '8px 20px',
    background: '#132d52',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  scrollArea: {
    flex: 1,
    overflowY: 'auto',
    WebkitOverflowScrolling: 'touch',
  },
  sectionLabel: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 1.2,
    color: 'var(--text3)',
    padding: '14px 16px 5px',
    textTransform: 'uppercase',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '11px 16px',
    cursor: 'pointer',
    borderBottom: '1px solid var(--border)',
    transition: 'background 0.1s',
    background: 'transparent',
  },
  rowUnread: {
    background: 'rgba(94, 237, 138, 0.04)',
  },
  rowActive: {
    background: 'rgba(94, 237, 138, 0.07)',
  },
  groupAvatar: {
    width: 42,
    height: 42,
    borderRadius: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
    fontWeight: 700,
    color: '#fff',
    flexShrink: 0,
  },
  rowContent: {
    flex: 1,
    minWidth: 0,
  },
  nameRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 6,
    marginBottom: 3,
  },
  name: {
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--text1)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    flex: 1,
    minWidth: 0,
  },
  timeLockRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  time: {
    fontSize: 11,
    color: 'var(--text3)',
  },
  lockIcon: {
    fontSize: 10,
  },
  publicBadge: {
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: 0.5,
    color: '#22c55e',
    background: 'rgba(34, 197, 94, 0.12)',
    padding: '1px 5px',
    borderRadius: 4,
  },
  preview: {
    fontSize: 13,
    color: 'var(--text3)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    flex: 1,
    minWidth: 0,
  },
  previewUnread: {
    color: 'var(--text1)',
    fontWeight: 500,
  },
  memberCount: {
    fontSize: 11,
    color: 'var(--text3)',
    flexShrink: 0,
    whiteSpace: 'nowrap',
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: '#5eed8a',
    flexShrink: 0,
    marginLeft: 4,
  },
  toggleRow: {
    padding: '10px 16px',
    cursor: 'pointer',
    borderBottom: '1px solid var(--border)',
    display: 'flex',
    alignItems: 'center',
  },
  toggleText: {
    fontSize: 13,
    color: 'var(--green, #22c55e)',
    fontWeight: 500,
  },
  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 24px',
    gap: 8,
  },
  emptyIcon: {
    fontSize: 36,
    marginBottom: 4,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: 'var(--text1)',
  },
  emptyHint: {
    fontSize: 13,
    color: 'var(--text3)',
    textAlign: 'center',
    lineHeight: 1.5,
  },
};
