export function getPortfolioStyles(t) {
  return {
    scroll: { flex: 1, overflowY: 'auto', background: t.bg, minHeight: '100%' },
    barNew: { display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', background: t.card, border: `1px solid ${t.green}25`, borderRadius: 12, marginBottom: 8 },
    barNewText: { flex: 1 },
    barNewTitle: { fontSize: 12, fontWeight: 700, color: t.text1 },
    barNewSub: { fontSize: 10, color: t.text3, marginTop: 2 },
    barNewBtn: { background: t.green, color: t.btnText, borderRadius: 8, padding: '8px 16px', fontSize: 12, fontWeight: 600, cursor: 'pointer', flexShrink: 0 },
    barActive: { display: 'flex', alignItems: 'center', gap: 8, padding: '8px 12px', background: t.card, border: `1px solid ${t.border}`, borderRadius: 12, marginBottom: 8 },
    barRank: { width: 30, height: 30, borderRadius: '50%', background: t.greenBg, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
    barRankText: { fontSize: 13, fontWeight: 800, color: t.green },
    barStats: { flex: 1 },
    barStatsTop: { display: 'flex', alignItems: 'center', gap: 6 },
    barStatsBottom: { display: 'flex', alignItems: 'center', gap: 6, fontSize: 10, color: t.text3, marginTop: 2, flexWrap: 'wrap' },
    barPortBtn: { background: t.greenBg, border: `1px solid ${t.green}40`, borderRadius: 8, padding: '6px 12px', fontSize: 10, fontWeight: 600, color: t.green, cursor: 'pointer', flexShrink: 0 },
    barPortBtnOpen: { background: t.green, color: t.btnText, borderColor: t.green },
    portDrop: { background: t.card, borderRadius: 12, border: `1px solid ${t.border}`, marginBottom: 8, overflow: 'hidden' },
    portCash: { display: 'flex' },
    portCashItem: { flex: 1, padding: '10px 8px', textAlign: 'center' },
    portCashLabel: { fontSize: 9, color: t.text3, fontWeight: 600, textTransform: 'uppercase', letterSpacing: 0.3 },
    portCashVal: { fontSize: 15, fontWeight: 700, color: t.text1, marginTop: 2 },
    portSecLabel: { fontSize: 9, fontWeight: 600, color: t.text3, textTransform: 'uppercase', letterSpacing: 0.4, padding: '8px 12px 4px', borderTop: `1px solid ${t.border}` },
    portPos: { display: 'flex', alignItems: 'center', padding: '8px 12px', borderBottom: `1px solid ${t.border}` },
    portPosTk: { fontSize: 13, fontWeight: 700, color: t.text1, width: 48 },
    portPosInfo: { flex: 1, fontSize: 11, color: t.text3 },
    portPosSell: { fontSize: 10, fontWeight: 600, color: t.red, background: t.redBg, border: `1px solid ${t.red}30`, padding: '5px 10px', borderRadius: 6, cursor: 'pointer', flexShrink: 0 },
    portBuyRow: { display: 'flex', gap: 4, padding: '8px 12px', borderTop: `1px solid ${t.border}` },
    portBuyInput: { flex: 1, background: t.surface, border: `1px solid ${t.border}`, borderRadius: 6, padding: '7px 8px', fontSize: 11, fontWeight: 600, color: t.text1, fontFamily: 'var(--font)', outline: 'none', letterSpacing: 0.4 },
    portBuyBtn: { background: t.green, color: t.btnText, border: 'none', borderRadius: 6, padding: '7px 12px', fontSize: 11, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)', flexShrink: 0 },
    portSearchRow: { padding: '8px 12px', borderBottom: `1px solid ${t.border}`, cursor: 'pointer', display: 'flex', gap: 6, alignItems: 'center' },
    portHistToggle: { fontSize: 10, fontWeight: 600, color: t.blue, textAlign: 'center', padding: '8px 12px', cursor: 'pointer', borderTop: `1px solid ${t.border}` },
    presetBtnSm: { flex: 1, padding: '6px 0', borderRadius: 5, border: `1px solid ${t.green}`, background: 'transparent', fontSize: 11, fontWeight: 600, color: t.green, cursor: 'pointer', fontFamily: 'var(--font)' },
    otherBtnSm: { flex: 1, padding: '6px 0', borderRadius: 5, border: `1px solid ${t.border}`, background: 'transparent', fontSize: 11, fontWeight: 600, color: t.text2, cursor: 'pointer', fontFamily: 'var(--font)' },
    customWrapSm: { flex: 1, display: 'flex', alignItems: 'center', background: t.card, border: `1px solid ${t.green}`, borderRadius: 5, padding: '0 6px' },
    customInputSm: { flex: 1, border: 'none', background: 'transparent', padding: '6px 0', fontSize: 12, fontWeight: 600, color: t.green, outline: 'none', fontFamily: 'var(--font)' },
    customBuySm: { background: t.green, color: t.btnText, border: 'none', borderRadius: 5, padding: '6px 12px', fontSize: 11, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)' },
    rankingsCard: { background: t.card, borderRadius: 12, border: `1px solid ${t.border}`, marginBottom: 8, overflow: 'hidden' },
    rankingsHdr: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px 12px 8px' },
    rankingsTitle: { fontSize: 11, fontWeight: 700, color: t.text1, textTransform: 'uppercase', letterSpacing: 0.5 },
    rankingsShow: { fontSize: 10, fontWeight: 600, color: t.blue, cursor: 'pointer' },
    topRow: { display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', borderTop: `1px solid ${t.border}`, cursor: 'pointer' },
    topMedal: { width: 24, height: 24, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 11, fontWeight: 700, color: '#fff', flexShrink: 0 },
    topInfo: { flex: 1, minWidth: 0 },
    topName: { fontSize: 13, fontWeight: 700, color: t.text1 },
    topNote: { fontSize: 10, color: t.text2, marginTop: 2, lineHeight: 1.4 },
    topBadge: { color: t.purple, fontWeight: 600 },
    topPct: { fontSize: 15, fontWeight: 700, flexShrink: 0 },
    rankDivider: { height: 1, background: t.border, margin: '2px 12px' },
    rankRow: { display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', border: '1px solid transparent', borderTop: `1px solid ${t.border}`, cursor: 'pointer' },
    rankNum: { width: 24, height: 24, borderRadius: '50%', background: t.surface, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 10, fontWeight: 600, color: t.text3, flexShrink: 0 },
    expandedPositions: { padding: '4px 12px 8px 48px', display: 'flex', flexWrap: 'wrap', gap: 6, borderTop: `1px solid ${t.border}` },
    expandedChip: { display: 'flex', gap: 4, alignItems: 'center', background: t.surface, border: `1px solid ${t.border}`, borderRadius: 6, padding: '4px 8px' },
    raceCard: { background: t.card, borderRadius: 12, border: `1px solid ${t.border}`, marginBottom: 8, overflow: 'hidden' },
    raceCardHdr: { padding: '10px 12px 6px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
    raceCardTitle: { fontSize: 11, fontWeight: 700, color: t.text1 },
    raceCardSub: { fontSize: 9, color: t.text3 },
    raceCardBody: { padding: '0 12px 10px' },
    learnCard: { background: t.card, borderRadius: 12, border: `1px solid ${t.purple}30`, marginBottom: 8, overflow: 'hidden' },
    learnCardHdr: { padding: '10px 12px 4px' },
    learnCardBody: { padding: '0 12px 10px' },
    skeleton: { height: 52, borderRadius: 12, marginBottom: 10, background: t.surface, animation: 'pulse 1.5s ease-in-out infinite' },
    smackWrap: { margin: 0, background: t.card, borderRadius: 12, border: `1px solid ${t.border}`, overflow: 'hidden' },
    smackHdr: { fontSize: 10, color: t.text1, textTransform: 'uppercase', letterSpacing: 0.4, fontWeight: 600, padding: '10px 12px 6px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
    smackLive: { fontSize: 8, color: t.green, background: t.greenBg, padding: '2px 6px', borderRadius: 3, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 3 },
    smackDot: { width: 5, height: 5, borderRadius: '50%', background: t.green },
    smackMsgs: { padding: '0 12px 6px', maxHeight: 150, overflowY: 'auto' },
    smackMsg: { padding: '6px 0', borderTop: `1px solid ${t.border}` },
    smackMsgTop: { display: 'flex', alignItems: 'flex-start', gap: 8 },
    smackAv: { width: 22, height: 22, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 9, fontWeight: 700, flexShrink: 0 },
    rxnRow: { display: 'flex', gap: 4, marginTop: 5, marginLeft: 30 },
    rxnPill: { display: 'flex', alignItems: 'center', gap: 3, padding: '2px 7px', borderRadius: 12, cursor: 'pointer', border: `0.5px solid ${t.border}`, background: t.surface, fontSize: 11 },
    rxnLit: { background: t.greenBg, borderColor: t.green },
    rxnCt: { fontSize: 10, fontWeight: 600, color: t.text3 },
    rxnAdd: { padding: '2px 6px', borderRadius: 12, cursor: 'pointer', fontSize: 11, border: `0.5px dashed ${t.border}`, background: 'transparent', color: t.text3, display: 'flex', alignItems: 'center', gap: 2 },
    smackInput: { display: 'flex', alignItems: 'center', gap: 6, padding: '8px 12px', borderTop: `1px solid ${t.border}`, background: t.surface },
    smackInputField: { flex: 1, background: t.card, border: `1px solid ${t.border}`, borderRadius: 8, padding: '8px 10px', fontSize: 12, color: t.text1, fontFamily: 'var(--font)', outline: 'none' },
    smackSendBtn: { background: t.green, color: t.btnText, border: 'none', borderRadius: 8, padding: '8px 12px', fontSize: 11, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)' },
  };
}
